-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = { "*.js", "*.ts", "*.vue", "*.py" }, -- Add other file types as needed
--   callback = function()
--     local formatter = require("formatter")
--     if formatter and formatter.format then
--       formatter.format()
--     else
--       print("Formatter not loaded or format function is nil")
--     end
--   end,
-- })
